CREATE TABLE IF NOT EXISTS testimonials (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  title VARCHAR(255),
  company VARCHAR(255),
  content TEXT NOT NULL,
  rating INT DEFAULT 5,
  image VARCHAR(500),
  featured BOOLEAN DEFAULT FALSE,
  status VARCHAR(50) DEFAULT 'published',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
